### ISSUE TITLE
团队章程1.0

### ISSUE THREAD

**Issue by jim-jinming** [jim-jinming/obstetrics_nursing_system#1]
为达成项目目标，凝聚团队力量，制定以下团队章程：

Z.1  以提高效率为纲。

Z.2  工作时间区间：

工作行为          | 区间始       | 区间末
消息通知          | 9:00          | 日落
提交评价           | 10:00       | 日落前3小时
决策                  | 11:00         | 日落前2小时
提交成果/报表  | 12:00        | 日落前1小时

相应工作仅在区间内进行。

Z.3  每周日日落前提交下周可用时间表，工作日内成员的上课时间与其它工作时间共计超过360分钟（9节课）即不分配任务，周末内成员的上课时间与其它工作时间超过240分钟（6节课）即不分配任务。	

Z.4  消息通知分为三类，一类为时效性强或重要性高的信息，用电话通知沟通；二类为时效灵活或重要性低的信息，使用QQ通知沟通；三类为时效性低、重要性高，需要存档及便于复查的资料/信息，使用邮件发送。

一类信息（电话）         | 二类信息（QQ）                       | 三类信息（e-mail）
离截止时间不到12小时 | 离截止时间大于12小时小于7天 | 离截止时间还有7个工作日及以上
有特定成员负责的信息 | 沟通、咨询类信息                      | 需要存档的信息

Z.5  所有工作成果除了在截止日期的相应区间内以邮箱向领队发送外，还需在 GitHub 上发布相应 Issue，其它成员需在两个工作日内（节假日及周末两天算一个工作日）在Issue评论处完成对作品的评价，包括评分和评语。	

Z.6  团队之内无阶级分别，所有队员皆有发表自己观点的自由，但团队的最终意见，由上述综合评分产生的权重决定。

Z.7  绩效 (P) 由上述权重 (W) 乘以工作时长 (T) 计算。 各项团队奖金将流入团队奖金池 (M) ，分配奖金时，首先计算各成员绩效的总和 ，然后将 M 除以总和 ，最终得到个体的奖金。

Z.8  第二课堂学分按需分配。

**Comment by jim-jinming** [comment]
投票格式

通过/不通过/弃权

评价（可选）：

**Comment by safehuard** [comment]
通过

**Comment by janniememory** [comment]
通过

**Comment by krylain** [comment]
通过

**Comment by openman44** [comment]
通过

**Comment by QiaoMR** [comment]
通过

**Comment by ChenxinliLily** [comment]
通过

**Comment by 281933559** [comment]
通过

**Comment by Star-zxy** [comment]
通过

**Comment by Yueblling** [comment]
通过

**Comment by syand** [comment]
弃权

**Comment by Zora5** [comment]
通过

**Comment by lianghongying0218** [comment]
通过

**Comment by jim-jinming** [comment]
团队章程1.0于2019年4月7日通过

**Comment by syand** [comment]
收到


------------------ 原始邮件 ------------------
发件人: "jinming"<notifications@github.com>;
发送时间: 2019年4月7日(星期天) 晚上7:23
收件人: "jim-jinming/obstetrics_nursing_system"<obstetrics_nursing_system@noreply.github.com>;
抄送: "sy"<564718986@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jim-jinming/obstetrics_nursing_system] 团队章程1.0 (#1)




Closed #1.

**Comment by Jessieing3** [comment]
通过

**Comment by krylain** [comment]
通过
