### ISSUE TITLE
Rating, ZhangXinyi-Transfering and inputting questionnaire, S.1.4.20.ZXY 

### ISSUE THREAD

**Issue by Star-zxy** [jim-jinming/obstetrics_nursing_system#12]
任务描述：
将附件中文末的繁体中文问卷（香港用），以符合中国大陆语言习惯的表达方式转写。输入到任意在线问卷收集网站（如问卷星），并妥善排版，另发送一份PDF版文档，于4月21日前提交。

任务成果：
1、[问卷.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3100925/default.pdf)
2、https://www.wjx.cn/m/38077650.aspx

任务收到时间：2019年4月15日，13:15
任务提交时间：2019年4月20日，12:05
任务花费时间：4小时

**Comment by Star-zxy** [comment]
问卷星中的问卷上传时个别符号显示有问题，改了之后重新发布:https://www.wjx.cn/m/38077650.aspx

**Comment by openman44** [comment]
30

**Comment by krylain** [comment]
20

**Comment by Zora5** [comment]
30

**Comment by lianghongying0218** [comment]
28

**Comment by Jessieing3** [comment]
28

**Comment by jim-jinming** [comment]
25

**Comment by safehuard** [comment]
25

**Comment by ChenxinliLily** [comment]
29

**Comment by Yueblling** [comment]
26

**Comment by janniememory** [comment]
27

**Comment by QiaoMR** [comment]
32

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
