### ISSUE TITLE
Rating,YangWenHan- simplified Chinese,s.1.4.21.YWH

### ISSUE THREAD

**Issue by safehuard** [jim-jinming/obstetrics_nursing_system#13]
任务描述：将附件中台湾地区编制的繁体中文版营养手册，转化为简体中文版，并适当调节用词，使其符合中国大陆的用语习惯。以 Word 文档格式提交。

任务成果：
[孕产期营养手册.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3100939/default.docx)
[婴儿营养手册.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3100940/default.docx)

任务收到时间：2019年4月15日，15：28
任务提交时间：2019年4月21日，13：25
任务花费时间：5小时

**Comment by openman44** [comment]
32 翻译内容多 在5小时内完成 完成程度高 除个别用词如小叮咛仍比较湾湾

**Comment by krylain** [comment]
28

**Comment by Zora5** [comment]
30

**Comment by lianghongying0218** [comment]
28

**Comment by Jessieing3** [comment]
30

**Comment by jim-jinming** [comment]
35

**Comment by ChenxinliLily** [comment]
35

**Comment by Star-zxy** [comment]
36

**Comment by Yueblling** [comment]
36

**Comment by janniememory** [comment]
35

**Comment by QiaoMR** [comment]
32

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
