### ISSUE TITLE
Rating,LiJiaqi- Dietary questionnaire,S.1.4.20.LJQ

### ISSUE THREAD

**Issue by openman44** [jim-jinming/obstetrics_nursing_system#14]
任务描述：参考附件香港饮食习惯调查文末的问卷，和附件学校饮食调查的问卷，浏览群问卷中相关文献，编制针对孕妇和产妇的饮食习惯调查，并发布于任意在线问卷网站（如问卷星），将链接与问卷的PDF版于4月21日前提交。

任务成果：
https://wj.qq.com/s2/3567681/b63c/
[孕产妇饮食调查.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3100177/default.pdf)

任务收到时间：2019年4月15日，15：25
任务提交时间：2019年4月20日，21：44
任务花费时间：4小时

**Comment by krylain** [comment]
28

**Comment by Zora5** [comment]
25

**Comment by lianghongying0218** [comment]
26

**Comment by Jessieing3** [comment]
26

**Comment by jim-jinming** [comment]
20

**Comment by safehuard** [comment]
22

**Comment by ChenxinliLily** [comment]
25

**Comment by Star-zxy** [comment]
24

**Comment by Yueblling** [comment]
2

**Comment by janniememory** [comment]
22

**Comment by QiaoMR** [comment]
24

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
