### ISSUE TITLE
Rating,zhenglin-compiling questionnaire

### ISSUE THREAD

**Issue by krylain** [jim-jinming/obstetrics_nursing_system#15]
任务描述： 编制问卷（少于25题），用于调查孕妇和产妇对于运动锻炼康复服务的使用情况。参考附件中的商家，参考 在线市场调查网站 https://cn.globaltestmarket.com 中的问卷的格式（可尝试注册，填写此网站提供的问卷）。将编制得到的问卷发布于任意在线问卷网站（如问卷星），并发送其链接与PDF文件。
任务成果：
[调查问卷.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3101156/default.pdf)

问卷星链接及二维码
https://www.wjx.cn/jq/38166348.aspx

![image](https://user-images.githubusercontent.com/49230338/56469456-9de84000-646c-11e9-926f-b20286e2fc97.png)

任务收到时间：2019年4月16日15:21
任务提交时间：2019年4月21日19:36
任务花费时间：7小时

**Comment by openman44** [comment]
28 可多调查年收入 其他内容丰富 问题直接简洁

**Comment by Zora5** [comment]
25

**Comment by lianghongying0218** [comment]
26

**Comment by Jessieing3** [comment]
28

**Comment by jim-jinming** [comment]
30

**Comment by safehuard** [comment]
26

**Comment by ChenxinliLily** [comment]
29

**Comment by Star-zxy** [comment]
29

**Comment by Yueblling** [comment]
30

**Comment by janniememory** [comment]
30

**Comment by QiaoMR** [comment]
27

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
