### ISSUE TITLE
Rating,LiangHongYing-Maternity Manual, S.1.4.21.LHY

### ISSUE THREAD

**Issue by lianghongying0218** [jim-jinming/obstetrics_nursing_system#16]
任务描述：
仔细阅读附件的两份报告，并搜集相关资料，编制针对产妇的知识手册。此手册将以类似于苹果公司产品说明书的形态设计（https://support.apple.com/zh-mo/guide/iphone/iph5a0b5b9c5/ios ） 以纸质形态与电子版并行发放，预计配图密度为50-80字/图，插图不仅包括人物，还包括器具、环境等，请合理想象插图的配置。其余元素自行定夺。限期4月21日。

任务成果：
PDF:[产妇知识手册.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3100869/default.pdf)
Word:[产妇知识手册.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3100870/default.docx)

任务收到时间：2019年04月15日,14:28
任务提交时间：2019年04月21日,11:23
任务花费时间：6小时

**Comment by jim-jinming** [comment]
60
内容详尽，近乎完美。
只是任务中规定的目标为「针对产妇」即针对产后妇女，无需整理孕妇所需知识。

**Comment by openman44** [comment]
60

**Comment by krylain** [comment]
62

**Comment by Zora5** [comment]
60
做的很棒嘞

**Comment by Jessieing3** [comment]
60内容很丰富

**Comment by safehuard** [comment]
60

**Comment by ChenxinliLily** [comment]
60工作量大，效率高，完成度好

**Comment by Star-zxy** [comment]
60

**Comment by Yueblling** [comment]
62内容详细确切

**Comment by janniememory** [comment]
70

**Comment by QiaoMR** [comment]
60

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
