### ISSUE TITLE
 Rating, GaoZiTing-logo-redraft, S.1.4.21.GZT

### ISSUE THREAD

**Issue by Jessieing3** [jim-jinming/obstetrics_nursing_system#17]
任务描述：
将附件logo_draft_2中的Logo以附件4.0中的画风重制，可适当调节元素，并尝试以矢量图的形式绘制。
![logo_draft_2](https://user-images.githubusercontent.com/49365800/56466149-729b2c00-643f-11e9-8e8d-7fd447d2e8cc.png)
![4 0](https://user-images.githubusercontent.com/49365800/56466142-2a7c0980-643f-11e9-8572-242dedff41f4.png)

任务成果：
![logo-redraft](https://user-images.githubusercontent.com/49365800/56466129-e6890480-643e-11e9-8996-dd8045e625d0.png)

任务收到时间：2019年4月15日，15:34
任务提交时间：2019年4月21日，13:43
任务花费时间：4小时

**Comment by openman44** [comment]
35 构图和谐 个人认为附件4.0最大优势的头发没有体现出来

**Comment by krylain** [comment]
34

**Comment by lianghongying0218** [comment]
36

**Comment by jim-jinming** [comment]
30

**Comment by safehuard** [comment]
35

**Comment by ChenxinliLily** [comment]
35 风格融合的很到位

**Comment by Star-zxy** [comment]
33

**Comment by Zora5** [comment]
33

**Comment by Yueblling** [comment]
30

**Comment by janniememory** [comment]
33

**Comment by QiaoMR** [comment]
32

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
