### ISSUE TITLE
Rating, ChenXinli-The interview report of teammates, S.1.4.21.CXL

### ISSUE THREAD

**Issue by ChenxinliLily** [jim-jinming/obstetrics_nursing_system#18]
「任务描述」针对任务完成情况问卷的结果，与标蓝的数据对应队员沟通，了解他们关于执行任务的问题和感受，以及如何理解“执行该任务的满意度”，为什么给出较低分数。
「任务成果」
[任务完成度队内访谈报告20190421（陈鑫丽）.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3100981/20190421.pdf)

「任务收到时间」2019年4月15日
「任务提交时间」2019年4月21日
「任务花费时间」3小时

**Comment by openman44** [comment]
34 访谈时客气礼貌 调查目的明确

**Comment by krylain** [comment]
30

**Comment by Zora5** [comment]
30
我的访谈里面，可以完善的地方的第一条被放在第二小点里面了

**Comment by lianghongying0218** [comment]
31

**Comment by Jessieing3** [comment]
32

**Comment by jim-jinming** [comment]
35
重点信息把握得很到位

**Comment by safehuard** [comment]
32

**Comment by Star-zxy** [comment]
31

**Comment by Yueblling** [comment]
34

**Comment by janniememory** [comment]
34

**Comment by QiaoMR** [comment]
35

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
