### ISSUE TITLE
Rating, WangWenJun-background drawing, S.1.4.21.WWJ

### ISSUE THREAD

**Issue by Zora5** [jim-jinming/obstetrics_nursing_system#19]
任务描述：
参考附件中的人物画风（色调、笔触），绘制与其风格一致的背景。背景至少包括：产房（医院）、休息室（医院）、门诊（医院）、起居室（住宅）、客厅（住宅）、厨房（住宅）。以png格式发送，限期4月21日。
任务成果：
![1](https://user-images.githubusercontent.com/49223177/56477706-37e6d180-64db-11e9-8f2c-21ca15251f5d.png)
![2](https://user-images.githubusercontent.com/49223177/56477762-a035b300-64db-11e9-9803-d924d5e97f22.png)
![3](https://user-images.githubusercontent.com/49223177/56477778-d70bc900-64db-11e9-8851-8176c12bc395.png)
![4](https://user-images.githubusercontent.com/49223177/56477779-da9f5000-64db-11e9-99c9-583a1e759978.png)

任务收到时间：2019年4月15日，14:03
任务提交时间：2019年4月21日，14:50
任务花费时间：6小时

**Comment by krylain** [comment]
30图片简洁，色彩鲜明

**Comment by lianghongying0218** [comment]
28

**Comment by Jessieing3** [comment]
30

**Comment by jim-jinming** [comment]
25

**Comment by janniememory** [comment]
20

**Comment by janniememory** [comment]
28

**Comment by safehuard** [comment]
28

**Comment by ChenxinliLily** [comment]
30

**Comment by Star-zxy** [comment]
28 色调和谐

**Comment by Yueblling** [comment]
28

**Comment by QiaoMR** [comment]
25

**Comment by openman44** [comment]
25

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
