### ISSUE TITLE
Rating, GaoZiTing-logo-draft, S.1.4.13.GZT

### ISSUE THREAD

**Issue by jim-jinming** [jim-jinming/obstetrics_nursing_system#2]
任务描述：
参考压缩包（R.1.4.7.1.1）中视觉识别系统的设计，也可参考网上其它素材，尝试绘制本项目的Logo（初稿），尝试为本项目取商标名，4月14日之内以png格式通过邮箱发送；可选元素包括，母亲、婴儿、健康（抽象）、运动（抽象）、自然（抽象）、机器与人的交互（抽象）

任务成果：
![logo_draft_1](https://user-images.githubusercontent.com/36655687/56076271-a3f17780-5e01-11e9-8f12-666cc8aa5ff4.png)
![logo_draft_2](https://user-images.githubusercontent.com/36655687/56076274-a9e75880-5e01-11e9-92be-44688a57769d.png)

任务收到时间：2019年4月7日，19:24
任务提交时间：2019年4月13日，13:53
任务花费时间：6小时

请评分（按照评分者对本项目的整体价值——如在淘宝上设计Logo的价格如何、效果如——来判断，将其价格除以任务花费时间，即为分数）

**Comment by jim-jinming** [comment]
33

**Comment by Star-zxy** [comment]
40

**Comment by krylain** [comment]
36

**Comment by Yueblling** [comment]
45

**Comment by openman44** [comment]
40

**Comment by lianghongying0218** [comment]
38
图一较有科技感，图二色彩鲜艳。

**Comment by Zora5** [comment]
40

**Comment by safehuard** [comment]
38

**Comment by QiaoMR** [comment]
38

**Comment by ChenxinliLily** [comment]
39
两个logo各具特色

**Comment by janniememory** [comment]
38

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
