### ISSUE TITLE
Rating, ZhangJiaMin- Obstetrics brochure S.1.4.22.ZJM

### ISSUE THREAD

**Issue by jim-jinming** [jim-jinming/obstetrics_nursing_system#20]
任务描述：
仔细阅读附件的两份报告，并搜集相关资料，编制针对孕妇的知识手册。此手册将以类似于苹果公司产品说明书的形态设计（https://support.apple.com/zh-mo/guide/iphone/iph5a0b5b9c5/ios ） 以纸质形态与电子版并行发放，预计配图密度为50-80字/图，插图不仅包括人物，还包括器具、环境等，请合理想象插图的配置。其余元素自行定夺。限期4月21日。

任务成果：[孕妇知识手册.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3106189/default.pdf)
任务收到时间：2019年04月15日,14:42
任务提交时间：2019年04月22日, 00:45
任务花费时间：12小时

**Comment by jim-jinming** [comment]
18
搜集信息时没有进行甄别，翻译腔重，文本质量较低
唯结构完整

**Comment by ChenxinliLily** [comment]
24 任务比较繁重，工作量大

**Comment by lianghongying0218** [comment]
22

**Comment by Star-zxy** [comment]
24 工作量较大

**Comment by Zora5** [comment]
22

**Comment by krylain** [comment]
23

**Comment by Yueblling** [comment]
20

**Comment by Jessieing3** [comment]
22

**Comment by QiaoMR** [comment]
20

**Comment by openman44** [comment]
22

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
