### ISSUE TITLE
Rating, ZhangXinyi-Exercise guidance compilation, S.1.4.27.ZXY

### ISSUE THREAD

**Issue by Star-zxy** [jim-jinming/obstetrics_nursing_system#21]
任务描述：
根据群问卷中视频video_20190408_095934 和 video_20190408_100346  以及 video_20190408_103339 编写文字的运动指导。

任务成果：
[运动指导.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3123532/default.pdf)

任务收到时间：2019年4月22日，18:18
任务提交时间：2019年4月27日，13:50
任务花费时间：2.5小时

**Comment by QiaoMR** [comment]
33

**Comment by jim-jinming** [comment]
30
步骤清晰，花费时间短

**Comment by krylain** [comment]
32

**Comment by janniememory** [comment]
32

**Comment by Jessieing3** [comment]
33

**Comment by lianghongying0218** [comment]
32

**Comment by Yueblling** [comment]
30

**Comment by openman44** [comment]
30

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
