### ISSUE TITLE
Rating,ChenYueBing-exercise guidance,S.1.4.27.CYB

### ISSUE THREAD

**Issue by Yueblling** [jim-jinming/obstetrics_nursing_system#22]
任务描述：根据群问卷中的视频 video_20190408_103002 和 video_20190408_103125 和 video_20190408_101842 以及 video_20190408_101715 编写文字的运动指导。
格式要求：PDF文档    截止日期：4月27日

任务成果：
[运动指导.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3123539/default.pdf)

任务收到时间：2019年4月22日18：15
任务提交时间：2019年4月27日13：57
任务花费时间：3小时

**Comment by QiaoMR** [comment]
38

**Comment by krylain** [comment]
34

**Comment by Star-zxy** [comment]
30

**Comment by janniememory** [comment]
34

**Comment by Jessieing3** [comment]
35

**Comment by lianghongying0218** [comment]
35

**Comment by openman44** [comment]
30

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
