### ISSUE TITLE
Rating,LiangHongYing-postpartum  recover, S.1.4.27.LHY

### ISSUE THREAD

**Issue by lianghongying0218** [jim-jinming/obstetrics_nursing_system#23]
任务描述：
https://mp.weixin.qq.com/s/7noN6hZbJwT6rHUEbl8RJQ 
参考此链接中的产品，搜寻关于产后康复和瑜伽的产品。尽可能多地收集其标准化动作，协会指导手册等信息。
格式要求：PDF文档
截止日期：4月27日

任务成果：
[产后恢复.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3123719/default.pdf)

任务收到时间：2019年04月22日,18:23
任务提交时间：2019年04月27日,15:27
任务花费时间：6小时

**Comment by jim-jinming** [comment]
35

**Comment by QiaoMR** [comment]
37

**Comment by QiaoMR** [comment]
33

**Comment by krylain** [comment]
34

**Comment by Star-zxy** [comment]
34

**Comment by janniememory** [comment]
35

**Comment by Jessieing3** [comment]
35

**Comment by openman44** [comment]
34

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
