### ISSUE TITLE
Ranting,ZhengLin-arrange files  S.1.4.28.ZL

### ISSUE THREAD

**Issue by krylain** [jim-jinming/obstetrics_nursing_system#24]
任务描述：校对附件中的两个文件，修改或删除不通畅的语句，将两个文件中的资料重新分配，组合成孕妇知识手册（包括孕期保健、自我监控、营养知识等）和产妇知识手册（产后保健知识、新生儿相关知识等）
任务成果：
[孕妇知识手册.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3124557/default.docx)
[产妇知识手册.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3124558/default.docx)
任务收到时间：2019年4月23日14:31
任务提交时间：2019年4月28日11:35
任务花费时间：10.5小时

**Comment by jim-jinming** [comment]
20
花费时间略长

**Comment by QiaoMR** [comment]
24

**Comment by Star-zxy** [comment]
22

**Comment by Zora5** [comment]
23

**Comment by janniememory** [comment]
22

**Comment by Jessieing3** [comment]
22

**Comment by lianghongying0218** [comment]
23

**Comment by openman44** [comment]
20

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
