### ISSUE TITLE
Rating, GaoZiTing-Market research, S.1.4.28.GZT

### ISSUE THREAD

**Issue by Jessieing3** [jim-jinming/obstetrics_nursing_system#25]
任务描述：
参考附件中的地址、联系方式等信息（无视其中的交通路线和计划），自行选择要考察的机构，预先确定交通计划，先用电话表明考察的意向（角色自行设定，可以为孕产妇家属或以保健机构调查为目标的学生等），利用工作日半天的时间前往市区考察其营业情况，具体的收费细则（如会员制、按节数收费、疗程收费等），保健方式等。完成考察后出具报告。
格式要求：PDF文档   截止时间：4月27日

任务成果：
[4.25考察报告.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3124630/4.25.pdf)

任务收到时间：2019年4月22日，18:05
任务提交时间：2019年4月26日，15:05
任务花费时间：8小时

**Comment by jim-jinming** [comment]
25
细节有待扩展

**Comment by QiaoMR** [comment]
28

**Comment by krylain** [comment]
27

**Comment by Star-zxy** [comment]
26

**Comment by Zora5** [comment]
27

**Comment by janniememory** [comment]
26

**Comment by lianghongying0218** [comment]
28

**Comment by openman44** [comment]
28

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
