### ISSUE TITLE
Rating,linyongqi-copy paiting,S.1.4.29.LYQ

### ISSUE THREAD

**Issue by QiaoMR** [jim-jinming/obstetrics_nursing_system#26]
任务描述：保持与上次作品一致的风格，绘制标准化人物形象，动作任意。标准化人物形象至少包括：普通妇女、孕早期妇女、孕中期妇女、孕晚期妇女、家属、伴侣、医生、护士。在本周内选择任意形象完成作品各一幅。在下周内完成所有形象至少各一幅。
任务成果：
![6 0](https://user-images.githubusercontent.com/49224390/56867270-e7f59680-6a15-11e9-85c1-8cc1809eeb4b.png)
![1 0](https://user-images.githubusercontent.com/49224390/56867271-e7f59680-6a15-11e9-8c0a-0c8c485fc25d.png)
![2 0](https://user-images.githubusercontent.com/49224390/56867272-e88e2d00-6a15-11e9-95d9-216d66d8779e.png)
![3 0](https://user-images.githubusercontent.com/49224390/56867273-e88e2d00-6a15-11e9-967c-1b42740fe0d4.png)
![4 0](https://user-images.githubusercontent.com/49224390/56867274-e88e2d00-6a15-11e9-843e-0fe1bd0a18bf.png)
![5 0](https://user-images.githubusercontent.com/49224390/56867275-e926c380-6a15-11e9-8125-eb205f2fc8f3.png)
任务收到时间：4.15
任务提交时间：4.29
任务花费时间：10h

**Comment by jim-jinming** [comment]
48
一流

**Comment by krylain** [comment]
50

**Comment by Star-zxy** [comment]
50

**Comment by Zora5** [comment]
50

**Comment by janniememory** [comment]
50

**Comment by Jessieing3** [comment]
50

**Comment by lianghongying0218** [comment]
49

**Comment by openman44** [comment]
45

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
