### ISSUE TITLE
Rating, WangWenJun-Market reseach, S.1.4.28.WWJ

### ISSUE THREAD

**Issue by Zora5** [jim-jinming/obstetrics_nursing_system#27]
任务描述：

参考附件中的地址、联系方式等信息（无视其中的交通路线和计划），自行选择要考察的机构，预先确定交通计划，先用电话表明考察的意向（角色自行设定，可以为孕产妇家属或以保健机构调查为目标的学生等），利用工作日半天的时间前往市区考察其营业情况，具体的收费细则（如会员制、按节数收费、疗程收费等），保健方式等。完成考察后出具报告。
格式要求：PDF文档
截止时间：4月27日

任务成果：
[孕产妇智能保健系统.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3133999/default.pdf)

任务收到时间：2019年4月22日
任务提交时间：2019年4月26日
任务花费时间：2小时

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
