### ISSUE TITLE
Rating,LiJiaqi-collecting information 

### ISSUE THREAD

**Issue by openman44** [jim-jinming/obstetrics_nursing_system#28]
任务描述：使用高德地图、苹果地图、谷歌地图、百度地图、大众点评、口碑搜索福州市内的运动保健机构（不限于针对孕产妇服务）。参考关键词：「产后修复」、「产后恢复」、「瑜伽」、「普拉提」等。注意，许多产后护理商家的主要商品实为护肤、按摩、理疗，而非目标人群的主动运动指导，望注意区分。搜寻到相关商家后再于天眼查、国家企业信用信息公示系统、全国中小企业股份转让系统等企业信息搜索引擎，获取其注册资本和经营范围等信息，是否为上市公司等。若为连锁公司，需获取其官网和尽可能多的宣传材料。若为上市公司（包括新三板），需获取其最近5年的定期报告，关于其盈利方式、营销手段、主要商品服务等做出解读。

任务成果：
[福州市相关机构列表.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3136958/default.pdf)
[福州市相关机构信息.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3136959/default.pdf)
[上市、连锁机构信息.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3136960/default.pdf)

任务收到时间：2019年4月29日，16：39
任务提交时间：2019年5月2日，14：57
任务花费：3小时

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
