### ISSUE TITLE
Rating,YangWenHan-verification,s.1.5.2.YWH

### ISSUE THREAD

**Issue by safehuard** [jim-jinming/obstetrics_nursing_system#29]
任务描述：通过搜索引擎，验证孕妇知识手册中（1-31页）信息的来源是否可靠，并注明可靠来源，删除段落或章节。将验证后的文本以章节或话题划分成400-800字的文章，发送给 林詠琪 
任务成果：
[产妇知识手册（上半部分）.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3137614/default.docx)
任务收到时间：2019年5月1日，15：04
任务提交时间：2019年5月2日，18：28
任务花费时间：3小时

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
