### ISSUE TITLE
Rating, ZhangXinyi-Telephone interview report, S.1.4.13.ZXY

### ISSUE THREAD

**Issue by Star-zxy** [jim-jinming/obstetrics_nursing_system#3]
任务描述：
制作访谈大纲，通过电话询访亲友中1.最近一年计划怀孕、2.正在孕期中的孕妇、3.最近6个月完成生产的产妇，了解她们对孕期营养、保健和产后营养、保健的知识的需求。至少访谈4位孕产妇，将访谈过程录音，将访谈过程概括成一篇报告，以PDF的格式通过邮件发送，期限为4月15日内。

任务成果：
[访谈报告.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3076015/default.pdf)

任务收到时间：2019年4月7日，14：52
任务提交时间：2019年4月13日，17：10
任务花费时间：15小时

**Comment by jim-jinming** [comment]
25。
此工作需要一定的专业知识，结合福州最低工资为18元每小时得出此分数。

**Comment by krylain** [comment]
30
需要耐心询问，找到适合人群，有专业知识。

**Comment by lianghongying0218** [comment]
28
需要专业知识，内容丰富。

**Comment by Yueblling** [comment]
26

**Comment by Zora5** [comment]
30
足够详细具体

**Comment by openman44** [comment]
28 完成目标

**Comment by Jessieing3** [comment]
30

**Comment by QiaoMR** [comment]
30

**Comment by ChenxinliLily** [comment]
30 工作量较大，需要访问并整理资料和归纳，完成度高。

**Comment by janniememory** [comment]
30

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
