### ISSUE TITLE
Rating,linyongqi-paiting,S.1.5.5.LYQ

### ISSUE THREAD

**Issue by QiaoMR** [jim-jinming/obstetrics_nursing_system#31]
任务描述：收到文章后考虑绘制合适的配图（需一张文章封面图和内文插图），然后打包发送给 王文俊 。
提交所有图片。
格式要求： 图片格式png， 压缩包格式 zip
截止日期： 5月5日
任务成果：
[任务成果.zip](https://github.com/jim-jinming/obstetrics_nursing_system/files/3145354/default.zip)
任务收到时间：5.1
任务提交时间：5.5
任务花费时间：5h

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
