### ISSUE TITLE
Rating,Zhenglin-Verify the maternal knowledge manual,S.1.5.10.ZL

### ISSUE THREAD

**Issue by krylain** [jim-jinming/obstetrics_nursing_system#32]
任务描述：通过搜索引擎，验证孕妇知识手册中31-56页信息的来源是否可靠，并注明可靠来源（论文、专业机构发表的文章、正规出版社出版的报刊）。
删除段落或章节：
1. 无可靠来源。
2. 并非面向孕妇（如产妇知识手册的最后一部分面向的是护士）。
3. 语句不通顺，不符合我们的用语习惯。
将验证后的文本以章节或话题划分成400-800字的文章，发送给 林詠琪 。
最终提交经验证过的文章。
格式要求： Word 文档
截止日期：5月12日
任务成果：[验证产妇知识手册.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3166416/default.docx)
任务收到时间：2019年5月7号
任务提交时间：2019年5月10号
任务花费时间：3小时

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
