### ISSUE TITLE
Rating,LiJiaqi-Team introduction 

### ISSUE THREAD

**Issue by openman44** [jim-jinming/obstetrics_nursing_system#33]
任务描述：
在5月8日收集到其它成员的简历后，编写用于商业计划书的团队介绍，可参考这几篇文章：http://www.sohu.com/a/219405278_99926643 / http://www.nutsbp.com/article/5d05cb90-6404-4ff6-b9ee-a85532a9b77d / http://www.nutsbp.com/article/bf96665d-4465-45dd-a25a-9d69eded8c37
 
任务成果：
[团队介绍.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3168677/default.docx)

任务收到时间：2019年5月6日(星期一) 下午5:48
任务完成时间：2019.5.11 13：58
任务花费：1小时

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
