### ISSUE TITLE
Rating,YangWenHan-time table,s.1.5.11.YWH

### ISSUE THREAD

**Issue by safehuard** [jim-jinming/obstetrics_nursing_system#34]
任务描述：查看以下两个链接中的文档
https://docs.qq.com/sheet/DZUVDV0VCVWNtUkRl?opendocxfrom=admin&id=DZUVDV0VCVWNtUkRl&coord=C52%24C52%240%240%240%240&tab=BB08J2
https://docs.qq.com/sheet/DZXpFQ1VacGZucHBt?opendocxfrom=admin&id=DZXpFQ1VacGZucHBt&coord=A1%24A1%240%240%240%240&tab=BB08J2
以及Github中的Issue，统计各成员的提交时间，并列出每人在区间外的提交次数。
任务成果：https://docs.qq.com/sheet/DUmZaeGdscnVIVVRM?opendocxfrom=admin&tab=BB08J2&coord=J18%24J18%240%240%240%240
任务收到时间：2019年5月8日 16：52
任务提交时间：2019年5月11日 14.38
任务花费时间：1h

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
