### ISSUE TITLE
Rating,ChenYueBing-reset scoring method,S.1.5.12.CYB

### ISSUE THREAD

**Issue by Yueblling** [jim-jinming/obstetrics_nursing_system#35]
任务描述：重制评分方式。
前端 https://wj.qq.com/s2/3659977/e27f/ 
后台https://wj.qq.com/edit.html?sid=3659977
参考以上模版，将过往的所有任务成果填装到问卷中，用于重新评分。模版中的第一题为矩阵量表题，工作成果可以在其标题中或使用附件题插入。
任务成果：
[评分.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3170058/default.docx)

任务收到时间：2019年5月7日16：16
任务提交时间：2019年5月12日20：45
任务花费时间：12h

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
