### ISSUE TITLE
Rating,ChenYueBing-postpartum sports text ,S.1.5.12.CYB

### ISSUE THREAD

**Issue by Yueblling** [jim-jinming/obstetrics_nursing_system#36]
任务描述：产后运动文案。查阅文献，列举产后运动的好处和运动不足的坏处，200字以内。
格式要求：Word截止日期：5月15日 18:40
任务成果：
[产后运动文案.docx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3178533/default.docx)

任务收到时间：2019年5月14日18：27
任务提交时间：2019年5月14日23：18
任务花费时间：2h

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
