### ISSUE TITLE
Rating,ZhengLin-Experience APP-daily yoga ,S1.5.17.ZL

### ISSUE THREAD

**Issue by krylain** [jim-jinming/obstetrics_nursing_system#37]
任务描述：使用每日瑜伽，参与其中至少6次课程（报销额度100元），从用户的角度撰写使用报告。
格式要求：PDF
截止日期：5月19日 18:38

任务成果：
[每日瑜伽使用报告.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3190852/default.pdf)

任务收到时间：2019年5月14日
任务提交时间：2019年5月17日
任务花费时间：3小时

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
