### ISSUE TITLE
Rating, WangWenJun-copy painting, S.1.4.13.WWJ

### ISSUE THREAD

**Issue by Zora5** [jim-jinming/obstetrics_nursing_system#4]
任务描述：
参考压缩包内文件，设计人物形象，确定人物色调，从12个临摹目标中任选2个，4月14日之内以png格式通过邮箱发送。要点：人物比例不超过正常人体解剖的+-20%（如七头身为标准东方比例，则画中形象在5.6-8.4头身之间）。关节部分明确，使浏览者易于模仿。其它部分，如是否描绘表情、是否绘制背景，自行决断。

任务成果：
临摹_1
临摹_2.1
临摹_2.2

![孕产妇智能保健系统1](https://user-images.githubusercontent.com/49223177/56078632-d2308080-5e1c-11e9-87b4-d8afe62db9c5.png)

![孕产妇智能保健系统2](https://user-images.githubusercontent.com/49223177/56078637-e3798d00-5e1c-11e9-9f98-0c3bdd62e3fd.png)

![孕产妇智能保健系统3](https://user-images.githubusercontent.com/49223177/56078625-c349ce00-5e1c-11e9-925e-a337afe34fbe.png)

任务收到时间：2019年4月7日，19:24
任务提交时间：2019年4月13日，11:47
任务花费时间：5小时

**Comment by jim-jinming** [comment]
19
此作品需要一定美术基础，但色彩搭配的和谐度不足

**Comment by krylain** [comment]
22
画人物有点难，感觉背景有点乱。

**Comment by lianghongying0218** [comment]
21
画面构图、背景不够精致。

**Comment by Yueblling** [comment]
24
略显粗糙。

**Comment by safehuard** [comment]
20

**Comment by QiaoMR** [comment]
25

**Comment by Jessieing3** [comment]
23

**Comment by openman44** [comment]
20 关键和部分肌肉线条明显

**Comment by ChenxinliLily** [comment]
24 动作刻画标准传神，易理解

**Comment by Star-zxy** [comment]
23重点突出，但整体略粗糙。

**Comment by janniememory** [comment]
25

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
