### ISSUE TITLE
Rating, LiJiaQi-collecting information, S.1.4.14.LJQ

### ISSUE THREAD

**Issue by openman44** [jim-jinming/obstetrics_nursing_system#5]
任务描述：搜寻国内国际的孕产妇保健服务提供商信息，整理成一个文档，包含以下内容：商品/商家名、服务价格、一般客户服务频次、营业范围、服务内容、服务形式。在4月15日内以PDF格式的文件发送至邮箱。
任务成果：
[调查.xlsx](https://github.com/jim-jinming/obstetrics_nursing_system/files/3076956/default.xlsx)
任务收到时间：2019年4月8日15:08
任务提交时间：2019年4月14日 10:40
任务花费时间：4小时

**Comment by jim-jinming** [comment]
28
此项任务对于使用电脑不熟练者可能需要6-7小时，因此在最低工资的基础上增加50%

**Comment by krylain** [comment]
33

**Comment by Yueblling** [comment]
28

**Comment by lianghongying0218** [comment]
28

**Comment by lianghongying0218** [comment]
28

**Comment by Zora5** [comment]
28

**Comment by safehuard** [comment]
30

**Comment by QiaoMR** [comment]
28

**Comment by Jessieing3** [comment]
32

**Comment by ChenxinliLily** [comment]
28

**Comment by Star-zxy** [comment]
30

**Comment by janniememory** [comment]
30

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
