### ISSUE TITLE
Rating,LiangHongYing-listing application format, S.1.4.14.LHY

### ISSUE THREAD

**Issue by lianghongying0218** [jim-jinming/obstetrics_nursing_system#6]
任务描述：
寻得FDA对于复健指导或运动器材的管理条例，并提取要点尝试撰写上市申请（或指明上市申请所需数据），4月15日内将文档以PDF格式通过邮件提交。

任务成果：
[Format for Traditional 510(k)s.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3077036/Format.for.Traditional.510.k.s.pdf)

任务收到时间：2019年04月08日,13:43
任务提交时间：2019年04月14日,13:03
任务花费时间：6小时

**Comment by jim-jinming** [comment]
38

**Comment by krylain** [comment]
45

**Comment by Yueblling** [comment]
42

**Comment by Zora5** [comment]
40

**Comment by safehuard** [comment]
40

**Comment by QiaoMR** [comment]
43

**Comment by openman44** [comment]
40

**Comment by Jessieing3** [comment]
43

**Comment by ChenxinliLily** [comment]
40

**Comment by Star-zxy** [comment]
43

**Comment by janniememory** [comment]
40

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
