### ISSUE TITLE
Rating,YangWenHan-access report,s.1.4.14.YWH

### ISSUE THREAD

**Issue by safehuard** [jim-jinming/obstetrics_nursing_system#7]
任务描述：以电话访问的形式，以孕妇、产妇的丈夫的身份，向福州市内的各孕产妇保健、服务机构询问服务内容、服务范围、服务形式、收费、频次，将访问过程录音，并整理得出访问的重点信息。将录音和PDF格式的文档在4月15日内通过邮件发送。
任务成果：

[福州市孕产妇保健、服务机构调查访问结果.zip](https://github.com/jim-jinming/obstetrics_nursing_system/files/3077053/default.zip)
任务收到时间：2019年4月8日，15.13
任务提交时间：2019年4月14日，13.52
任务花费时间：8小时

**Comment by jim-jinming** [comment]
24

**Comment by krylain** [comment]
30

**Comment by Yueblling** [comment]
26

**Comment by lianghongying0218** [comment]
28
整理清晰。

**Comment by Zora5** [comment]
28

**Comment by QiaoMR** [comment]
27

**Comment by openman44** [comment]
28

**Comment by Jessieing3** [comment]
28

**Comment by ChenxinliLily** [comment]
30

**Comment by Star-zxy** [comment]
29

**Comment by janniememory** [comment]
28

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
