### ISSUE TITLE
Rating,LinYongqi-copy paiting,S.1.4.14.LYQ

### ISSUE THREAD

**Issue by QiaoMR** [jim-jinming/obstetrics_nursing_system#8]
任务描述
参考压缩包内文件，设计人物形象，确定人物色调，从12个临摹目标中任选4个，4月14日之内以png格式通过邮箱发送。要点：人物比例不超过正常人体解剖的+-20%（如七头身为标准东方比例，则画中形象在5.6-8.4头身之间）。关节部分明确，使浏览者易于模仿。其它部分，如是否描绘表情、是否绘制背景，自行决断。
任务成果
![1 0](https://user-images.githubusercontent.com/49224390/56089247-98b25080-5ec2-11e9-8c32-3ba779ee138e.png)
![2 0](https://user-images.githubusercontent.com/49224390/56089248-98b25080-5ec2-11e9-9a12-d48c00dec396.png)
![3 0](https://user-images.githubusercontent.com/49224390/56089249-994ae700-5ec2-11e9-83f9-100d0334d355.png)
![4 0](https://user-images.githubusercontent.com/49224390/56089250-994ae700-5ec2-11e9-84c4-1bf5cacc126a.png)
任务收到时间：2019.4.7
任务提交时间：2019.4.14
任务花费时间：10h

**Comment by jim-jinming** [comment]
30
后两张图画的色彩和阴影处理极佳，色调柔和

**Comment by krylain** [comment]
30

**Comment by Yueblling** [comment]
36

**Comment by lianghongying0218** [comment]
35
画面柔和。

**Comment by Zora5** [comment]
35
色彩搭配的好看

**Comment by safehuard** [comment]
32

**Comment by openman44** [comment]
36 头发好看

**Comment by Jessieing3** [comment]
35整体很协调

**Comment by ChenxinliLily** [comment]
34 个人觉得可以加一些简单的面部表情

**Comment by Star-zxy** [comment]
36

**Comment by janniememory** [comment]
34

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
