### ISSUE TITLE
Rating,zhangjiamin-patent filing,S.1.4.14.ZJM

### ISSUE THREAD

**Issue by janniememory** [jim-jinming/obstetrics_nursing_system#9]
[用于物理疗法以及复健 的影像游戏的个人数字 训练器材.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3077228/default.pdf)
[人体康复过程自动识别方法及装置.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3077229/default.pdf)
[病患专用复健电玩.pdf](https://github.com/jim-jinming/obstetrics_nursing_system/files/3077230/default.pdf)
任务描述:阅读专利文档，概括专利所实现的背景、实施方法、重点功能
任务成果:3 件专利分别概括为3 个 PDF文件
任务收到时间:2019年4月8日14:02
任务提交时间:2019年4月14日
任务花费时间:7小时

**Comment by jim-jinming** [comment]
26
概括得较为完善

**Comment by krylain** [comment]
30

**Comment by Yueblling** [comment]
24

**Comment by lianghongying0218** [comment]
28

**Comment by Zora5** [comment]
25

**Comment by safehuard** [comment]
25

**Comment by QiaoMR** [comment]
25

**Comment by openman44** [comment]
28

**Comment by Jessieing3** [comment]
27

**Comment by ChenxinliLily** [comment]
28

**Comment by Star-zxy** [comment]
27

**Comment by jim-jinming** [comment]
本项目不再使用Issue作为评分收集工具
